### Cocoa Code Comparison
### Motivation:
###     Compare Cococa v.s. ROMAN Y3 public result (CosmoSIS)
###     - data vector: ROMAN 3x2
###     - scale cut: baseline (not LCDM-optimized)
###     - number of Qs marginalized: 0
### -----------------------------------------------------------------
### cosmology: baseline (omegam, As, ns, omegab, H0)
### systematics: 
###     - shear calibration bias: multiplicative, 
###     - photo-z uncertainty: gaussian
###     - galaxy bias: linear bias
###     - intrinsic alignment: TATT
### analysis choice:
###     - covariance from public release
### external probes: None
### data vector: ROMAN 3x2pt

timing: True
debug: False
stop_at_error: False

likelihood:
  roman_real_y1.roman_real_y1_3x2pt:
    path: ./projects/roman_real_y1/data
    #path: data
    data_file: roman_real.dataset
    integration_accuracy: 0
    
    
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.65
    proposal: 0.4
    latex: 10^9 A_\mathrm{s}
    drop: true
    renames: A
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 5
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.04
      scale: 0.004
    proposal: 0.004
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.3
      scale: 0.02
    proposal: 0.02
    latex: \Omega_\mathrm{m}
    drop: true
  mnu:
    value: 0.06
    latex: \m_\\nu
  w:
    value: -1
    latex: w_{0,\mathrm{DE}}
  wa:
    value: 0.0
    latex: w_{a,\mathrm{DE}}
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  # ------------------------------------------------------------------
  # ------------- Derived Parameters ---------------------------------
  # ------------------------------------------------------------------
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
  omegal:
    latex: \Omega_\Lambda
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  s8:
    derived: 'lambda sigma8, omegam: sigma8*(omegam/0.3)**0.5'
    latex: S_8
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
  rdrag:
    latex: r_\mathrm{drag}
  yheused:
    latex: Y_P^\mathrm{BBN}
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  # ------------------------------------------------------------------
  # ROMAN-Y1 3x2 nuissance parameter begins
  # ------------------------------------------------------------------

  # galaxy bias: linear bias
  # ========================
  # same as default, flat prior [0.8, 3.0] 

  # intrinsic alignment: TATT
  # ========================
  # as default, ROMAN_A1_1 [-5, 5]; ROMAN_A1_2 [-5, 5]
  # fiducial value: 0.6, -1.5
  ROMAN_A2_1: #TATT, not used for Y1
    prior:
      min: -5.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.0
      scale: 0.2
    proposal: 0.2
    latex: A_\mathrm{2-IA,ROMAN}^1 
  ROMAN_A2_2: #TATT, not used for Y1
    prior:
      min: -5.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.0
      scale: 0.2
    proposal: 0.2
    latex: A_\mathrm{2-IA,ROMAN}^2
  ROMAN_BTA_1: #TATT, not used for Y1
    prior:
      min: 0.0
      max: 2.0
    ref:
      dist: norm
      loc: 1.0
      scale: 0.1
    proposal: 0.1
    latex: A_\mathrm{BTA-IA,ROMAN}^1

  # photo-z uncertainty: gaussian
  # =============================
  # Source galaxies photo-z errors
  ROMAN_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.018
    ref:
      dist: norm
      loc: 0.0
      scale: 0.018
    proposal: 0.009
    latex: \Delta z_\mathrm{s,ROMAN}^1
  ROMAN_DZ_S2:
    prior:
      dist: norm
      loc: 0.0 
      scale: 0.015
    ref:
      dist: norm
      loc: 0.0
      scale: 0.015
    proposal: 0.007
    latex: \Delta z_\mathrm{s,ROMAN}^2
  ROMAN_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.011
    ref:
      dist: norm
      loc: 0.0
      scale: 0.011
    proposal: 0.005
    latex: \Delta z_\mathrm{s,ROMAN}^3
  ROMAN_DZ_S4:
    prior:
      dist: norm
      loc: 0.0 
      scale: 0.017
    ref:
      dist: norm
      loc: 0.0
      scale: 0.017
    proposal: 0.008
    latex: \Delta z_\mathrm{s,ROMAN}^4
  # shear calibration bias: multiplicative
  # ======================================
  ROMAN_M1:
    prior:
      dist: norm
      loc: -0.006
      scale: 0.009
    ref:
      dist: norm
      loc: -0.006
      scale: 0.009
    proposal: 0.004
    latex: m_\mathrm{ROMAN}^1
  ROMAN_M2:
    prior:
      dist: norm
      loc: -0.020
      scale: 0.008
    ref:
      dist: norm
      loc: -0.020
      scale: 0.008
    proposal: 0.004
    latex: m_\mathrm{ROMAN}^2
  ROMAN_M3:
    prior:
      dist: norm
      loc: -0.024
      scale: 0.008
    ref:
      dist: norm
      loc: -0.024
      scale: 0.008
    proposal: 0.004
    latex: m_\mathrm{ROMAN}^3
  ROMAN_M4:
    prior:
      dist: norm
      loc: -0.037
      scale: 0.008
    ref:
      dist: norm
      loc: -0.037
      scale: 0.008
    proposal: 0.004
    latex: m_\mathrm{ROMAN}^4
  # baryon effects: scale cut

  # Fixed params of Maglim bin 5-6
  ROMAN_DZ_L5:
    value: 0.002
    latex: \Delta z_\mathrm{l,ROMAN}^5
  ROMAN_DZ_L6:
    value: 0.002
    latex: \Delta z_\mathrm{l,ROMAN}^6
  ROMAN_STRETCH_L5:
    value: 1.08
    latex: \sigma z_\mathrm{l,ROMAN}^5
  ROMAN_STRETCH_L6:
    value: 0.845
    latex: \sigma z_\mathrm{l,ROMAN}^6
  ROMAN_B1_5:
    value: 2.3
    latex: b_\mathrm{1-ROMAN}^5
  ROMAN_B1_6:
    value: 2.3
    latex: b_\mathrm{1-ROMAN}^6
  

  # ------------------------------------------------------------------
  # ROMAN-Y1 3x2 nuissance parameter ends
  # ------------------------------------------------------------------

theory:
  camb:
    path: ./external_modules/code/CAMB
    use_renames: True
    extra_args:
      halofit_version: bird
      AccuracyBoost: 1.1
      lens_potential_accuracy: 1.1
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 20

sampler:
  mcmc:
    # ---------------------------------------------------------------------
    # File (w/ path) or matrix defining a covariance matrix for the proposal:
    # - null (default): will be generated from params info (prior and proposal)
    # - matrix: remember to set `covmat_params` to the parameters in the matrix
    #covmat: ./EXAMPLE_MCMC1.covmat
    covmat_params:
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # Proposal covariance matrix learning
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    learn_proposal: True
    # Don't learn if convergence better than...
    learn_proposal_Rminus1_min: 0.03
    # Don't learn if convergence is worse than...
    learn_proposal_Rminus1_max: 50.
    # (even earlier if a param is not in the given covariance matrix)
    learn_proposal_Rminus1_max_early: 2000.
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # Convergence and stopping
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # Maximum number of posterior evaluations
    max_samples: .inf
    # Gelman-Rubin R-1 on means
    Rminus1_stop: 0.02
    # Gelman-Rubin R-1 on std deviations
    Rminus1_cl_stop: 0.2
    Rminus1_cl_level: 0.95
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # Exploiting speed hierarchy
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    measure_speeds: False
    drag: False
    #oversample_power: 0.25
    #oversample_thin: True
    #blocking:
    #  - [1,
    #      [
    #         As_1e9, ns, H0, omegab, omegam
    #      ]
    #    ]
    #  - [3,
    #      [
    #        ROMAN_DZ_S1, ROMAN_DZ_S2, ROMAN_DZ_S3, ROMAN_DZ_S4, 
    #        ROMAN_A1_1, ROMAN_A1_2, ROMAN_A2_1, ROMAN_A2_2, ROMAN_BTA_1,
    #        ROMAN_DZ_L1, ROMAN_DZ_L2, ROMAN_DZ_L3, ROMAN_DZ_L4,
    #        ROMAN_STRETCH_L1, ROMAN_STRETCH_L2, ROMAN_STRETCH_L3, ROMAN_STRETCH_L4
    #      ]
    #    ]
    #  - [25,
    #      [
    #        ROMAN_M1, ROMAN_M2, ROMAN_M3, ROMAN_M4,
    #        ROMAN_B1_1, ROMAN_B1_2, ROMAN_B1_3, ROMAN_B1_4
    #      ]
    #    ]
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # Avoid chain getting suck forever
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    max_tries: 10000
    burn_in: 0
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    # When no MPI used, number of fractions of the chain to compare
    # ---------------------------------------------------------------------
    # ---------------------------------------------------------------------
    Rminus1_single_split: 4

emulator:
  io:
    ###savedir: ./projects/desy1xplanck/emulator
    savedir: /groups/behroozi/hbowden/emulator_output
    save_train_data: true
    save_intermediate_model: true
    chainname: emu_testing_chain
  #shear_calib:
  #  mask: ./projects/desy1xplanck/data/emu_data/DESY3xPLKR4_Maglim_baseline_Ntheta30_shear_calib_mask.npy
  #  prior_std: 0.0091,0.0078,0.0076,0.0076
  #baryons:
    #n_pcas_baryon: 1
    #prior_Q1: -6.,20.
    #prior_Q1: 0.0, 7.0
    #prior_Q2: -4.,4.
  # galaxy_bias:
  #   mask: ./projects/desy1xplanck/data/emu_data/DESY3xPLKR4_Maglim_baseline_Ntheta30_linear_gbias_mask.npy
  #   bias_fid: 1.5,1.8,1.8,1.9,2.3,2.3
  #   bias_prior: 0.8, 3.0
  init_sample:
    type: "lhs" # "lhs" or "gaussian"
    # LHS section
    lhs_n: 10 # Latin-Hyper Sample size
    # Gaussian section
    #gauss_cov: ./EXAMPLE_MCMC1.covmat
    #gauss_temp_train: 128 # training dataset temperature
    #n_train: 1000000
    #gauss_shift_train: 
     # omegam: 0.0
     # sigma8: 0.0
    #gauss_temp_valid: 64  # validation dataset temperature
    #n_valid: 10000
    #gauss_shift_valid:
  training:
    emu_type: nn
    nn_model: 6
    #dv_fid: ./projects/desy1xplanck/data/data_vectors/xi_DESY3xPLKR4_6x2pt_Maglim_baseline_Ntheta30_dmo.emufid
    chi_sq_cut: 1.0e+5
    n_train_iter: 1
    batch_size: 256
    n_epochs: 200
    loss_type: "hyperbola"
    #loss_type: "clipped_mean"
    #loss_type: "mean"
    learning_rate: 1.0e-3
    weight_decay: 1.0e-3
    reduce_lr: True
  derived:
    sigma8_fid: 0.827706
    sigma8_std: 0.01
  sampling:
    ### This mask is different from the mask in the dataset file
    ### Dataset mask: can short-cut model vector evaluation
    ### This mask: can not short-cut mv calculation, applied in EmuSampler likelihood calc
    ### BUT setting a different mask here would block the gradient back propagation, thus
    ### the cutted scales are note learnt. 
    #scalecut_mask: ./projects/desy1xplanck/data/masks/xi_DESY3xPLKR4_6x2pt_Maglim_baseline_Ntheta30_emucons.mask
    n_mcmc: 1000000
    #n_mcmc: 10000
    n_emcee_walkers: 100
    n_burn_in: 500000
    #n_burn_in: 5000
    n_thin: 10
    # temper0: 0.02
    # temper_increment: 0.05

output: /groups/behroozi/hbowden/cocoa_cpu/Cocoa/projects/roman_real_y1/emulator_output/chains/Jtest